/**
 * @file display.c
 *
 * @brief This source file was generated by cantools version 43.0.2 Tue Sep  1 22:13:43 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "display.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int display_diagnostics_pack(
    uint8_t *dst_p,
    const struct display_diagnostics_t *src_p,
    size_t size)
{
    uint16_t cpu_temperature;

    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    cpu_temperature = (uint16_t)src_p->cpu_temperature;
    dst_p[0] |= pack_right_shift_u16(cpu_temperature, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(cpu_temperature, 0u, 0xffu);

    return (2);
}

int display_diagnostics_unpack(
    struct display_diagnostics_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t cpu_temperature;

    if (size < 2u) {
        return (-EINVAL);
    }

    cpu_temperature = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    cpu_temperature |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->cpu_temperature = (int16_t)cpu_temperature;

    return (0);
}

int display_diagnostics_init(struct display_diagnostics_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct display_diagnostics_t));

    return 0;
}

int16_t display_diagnostics_cpu_temperature_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double display_diagnostics_cpu_temperature_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool display_diagnostics_cpu_temperature_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 10000));
}

bool display_diagnostics_cpu_temperature_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 100.0));
}

int display_neopixel_pack(
    uint8_t *dst_p,
    const struct display_neopixel_t *src_p,
    size_t size)
{
    if (size < 64u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 64);

    dst_p[0] |= pack_right_shift_u32(src_p->led_00, 16u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->led_00, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u32(src_p->led_00, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->led_01, 16u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(src_p->led_01, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u32(src_p->led_01, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->led_02, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->led_02, 8u, 0xffu);
    dst_p[8] |= pack_left_shift_u32(src_p->led_02, 0u, 0xffu);
    dst_p[9] |= pack_right_shift_u32(src_p->led_03, 16u, 0xffu);
    dst_p[10] |= pack_right_shift_u32(src_p->led_03, 8u, 0xffu);
    dst_p[11] |= pack_left_shift_u32(src_p->led_03, 0u, 0xffu);
    dst_p[12] |= pack_right_shift_u32(src_p->led_04, 16u, 0xffu);
    dst_p[13] |= pack_right_shift_u32(src_p->led_04, 8u, 0xffu);
    dst_p[14] |= pack_left_shift_u32(src_p->led_04, 0u, 0xffu);
    dst_p[15] |= pack_right_shift_u32(src_p->led_05, 16u, 0xffu);
    dst_p[16] |= pack_right_shift_u32(src_p->led_05, 8u, 0xffu);
    dst_p[17] |= pack_left_shift_u32(src_p->led_05, 0u, 0xffu);
    dst_p[18] |= pack_right_shift_u32(src_p->led_06, 16u, 0xffu);
    dst_p[19] |= pack_right_shift_u32(src_p->led_06, 8u, 0xffu);
    dst_p[20] |= pack_left_shift_u32(src_p->led_06, 0u, 0xffu);
    dst_p[21] |= pack_right_shift_u32(src_p->led_07, 16u, 0xffu);
    dst_p[22] |= pack_right_shift_u32(src_p->led_07, 8u, 0xffu);
    dst_p[23] |= pack_left_shift_u32(src_p->led_07, 0u, 0xffu);
    dst_p[24] |= pack_right_shift_u32(src_p->led_08, 16u, 0xffu);
    dst_p[25] |= pack_right_shift_u32(src_p->led_08, 8u, 0xffu);
    dst_p[26] |= pack_left_shift_u32(src_p->led_08, 0u, 0xffu);
    dst_p[27] |= pack_right_shift_u32(src_p->led_09, 16u, 0xffu);
    dst_p[28] |= pack_right_shift_u32(src_p->led_09, 8u, 0xffu);
    dst_p[29] |= pack_left_shift_u32(src_p->led_09, 0u, 0xffu);
    dst_p[30] |= pack_right_shift_u32(src_p->led_10, 16u, 0xffu);
    dst_p[31] |= pack_right_shift_u32(src_p->led_10, 8u, 0xffu);
    dst_p[32] |= pack_left_shift_u32(src_p->led_10, 0u, 0xffu);
    dst_p[33] |= pack_right_shift_u32(src_p->led_11, 16u, 0xffu);
    dst_p[34] |= pack_right_shift_u32(src_p->led_11, 8u, 0xffu);
    dst_p[35] |= pack_left_shift_u32(src_p->led_11, 0u, 0xffu);
    dst_p[36] |= pack_right_shift_u32(src_p->led_12, 16u, 0xffu);
    dst_p[37] |= pack_right_shift_u32(src_p->led_12, 8u, 0xffu);
    dst_p[38] |= pack_left_shift_u32(src_p->led_12, 0u, 0xffu);
    dst_p[39] |= pack_right_shift_u32(src_p->led_13, 16u, 0xffu);
    dst_p[40] |= pack_right_shift_u32(src_p->led_13, 8u, 0xffu);
    dst_p[41] |= pack_left_shift_u32(src_p->led_13, 0u, 0xffu);
    dst_p[42] |= pack_right_shift_u32(src_p->led_14, 16u, 0xffu);
    dst_p[43] |= pack_right_shift_u32(src_p->led_14, 8u, 0xffu);
    dst_p[44] |= pack_left_shift_u32(src_p->led_14, 0u, 0xffu);
    dst_p[45] |= pack_right_shift_u32(src_p->led_15, 16u, 0xffu);
    dst_p[46] |= pack_right_shift_u32(src_p->led_15, 8u, 0xffu);
    dst_p[47] |= pack_left_shift_u32(src_p->led_15, 0u, 0xffu);
    dst_p[48] |= pack_right_shift_u32(src_p->led_16, 16u, 0xffu);
    dst_p[49] |= pack_right_shift_u32(src_p->led_16, 8u, 0xffu);
    dst_p[50] |= pack_left_shift_u32(src_p->led_16, 0u, 0xffu);
    dst_p[51] |= pack_right_shift_u32(src_p->led_17, 16u, 0xffu);
    dst_p[52] |= pack_right_shift_u32(src_p->led_17, 8u, 0xffu);
    dst_p[53] |= pack_left_shift_u32(src_p->led_17, 0u, 0xffu);
    dst_p[54] |= pack_right_shift_u32(src_p->led_18, 16u, 0xffu);
    dst_p[55] |= pack_right_shift_u32(src_p->led_18, 8u, 0xffu);
    dst_p[56] |= pack_left_shift_u32(src_p->led_18, 0u, 0xffu);
    dst_p[57] |= pack_right_shift_u32(src_p->led_19, 16u, 0xffu);
    dst_p[58] |= pack_right_shift_u32(src_p->led_19, 8u, 0xffu);
    dst_p[59] |= pack_left_shift_u32(src_p->led_19, 0u, 0xffu);
    dst_p[60] |= pack_right_shift_u32(src_p->led_20, 16u, 0xffu);
    dst_p[61] |= pack_right_shift_u32(src_p->led_20, 8u, 0xffu);
    dst_p[62] |= pack_left_shift_u32(src_p->led_20, 0u, 0xffu);
    dst_p[63] |= pack_left_shift_u8(src_p->brightness, 0u, 0xffu);

    return (64);
}

int display_neopixel_unpack(
    struct display_neopixel_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 64u) {
        return (-EINVAL);
    }

    dst_p->led_00 = unpack_left_shift_u32(src_p[0], 16u, 0xffu);
    dst_p->led_00 |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->led_00 |= unpack_right_shift_u32(src_p[2], 0u, 0xffu);
    dst_p->led_01 = unpack_left_shift_u32(src_p[3], 16u, 0xffu);
    dst_p->led_01 |= unpack_left_shift_u32(src_p[4], 8u, 0xffu);
    dst_p->led_01 |= unpack_right_shift_u32(src_p[5], 0u, 0xffu);
    dst_p->led_02 = unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->led_02 |= unpack_left_shift_u32(src_p[7], 8u, 0xffu);
    dst_p->led_02 |= unpack_right_shift_u32(src_p[8], 0u, 0xffu);
    dst_p->led_03 = unpack_left_shift_u32(src_p[9], 16u, 0xffu);
    dst_p->led_03 |= unpack_left_shift_u32(src_p[10], 8u, 0xffu);
    dst_p->led_03 |= unpack_right_shift_u32(src_p[11], 0u, 0xffu);
    dst_p->led_04 = unpack_left_shift_u32(src_p[12], 16u, 0xffu);
    dst_p->led_04 |= unpack_left_shift_u32(src_p[13], 8u, 0xffu);
    dst_p->led_04 |= unpack_right_shift_u32(src_p[14], 0u, 0xffu);
    dst_p->led_05 = unpack_left_shift_u32(src_p[15], 16u, 0xffu);
    dst_p->led_05 |= unpack_left_shift_u32(src_p[16], 8u, 0xffu);
    dst_p->led_05 |= unpack_right_shift_u32(src_p[17], 0u, 0xffu);
    dst_p->led_06 = unpack_left_shift_u32(src_p[18], 16u, 0xffu);
    dst_p->led_06 |= unpack_left_shift_u32(src_p[19], 8u, 0xffu);
    dst_p->led_06 |= unpack_right_shift_u32(src_p[20], 0u, 0xffu);
    dst_p->led_07 = unpack_left_shift_u32(src_p[21], 16u, 0xffu);
    dst_p->led_07 |= unpack_left_shift_u32(src_p[22], 8u, 0xffu);
    dst_p->led_07 |= unpack_right_shift_u32(src_p[23], 0u, 0xffu);
    dst_p->led_08 = unpack_left_shift_u32(src_p[24], 16u, 0xffu);
    dst_p->led_08 |= unpack_left_shift_u32(src_p[25], 8u, 0xffu);
    dst_p->led_08 |= unpack_right_shift_u32(src_p[26], 0u, 0xffu);
    dst_p->led_09 = unpack_left_shift_u32(src_p[27], 16u, 0xffu);
    dst_p->led_09 |= unpack_left_shift_u32(src_p[28], 8u, 0xffu);
    dst_p->led_09 |= unpack_right_shift_u32(src_p[29], 0u, 0xffu);
    dst_p->led_10 = unpack_left_shift_u32(src_p[30], 16u, 0xffu);
    dst_p->led_10 |= unpack_left_shift_u32(src_p[31], 8u, 0xffu);
    dst_p->led_10 |= unpack_right_shift_u32(src_p[32], 0u, 0xffu);
    dst_p->led_11 = unpack_left_shift_u32(src_p[33], 16u, 0xffu);
    dst_p->led_11 |= unpack_left_shift_u32(src_p[34], 8u, 0xffu);
    dst_p->led_11 |= unpack_right_shift_u32(src_p[35], 0u, 0xffu);
    dst_p->led_12 = unpack_left_shift_u32(src_p[36], 16u, 0xffu);
    dst_p->led_12 |= unpack_left_shift_u32(src_p[37], 8u, 0xffu);
    dst_p->led_12 |= unpack_right_shift_u32(src_p[38], 0u, 0xffu);
    dst_p->led_13 = unpack_left_shift_u32(src_p[39], 16u, 0xffu);
    dst_p->led_13 |= unpack_left_shift_u32(src_p[40], 8u, 0xffu);
    dst_p->led_13 |= unpack_right_shift_u32(src_p[41], 0u, 0xffu);
    dst_p->led_14 = unpack_left_shift_u32(src_p[42], 16u, 0xffu);
    dst_p->led_14 |= unpack_left_shift_u32(src_p[43], 8u, 0xffu);
    dst_p->led_14 |= unpack_right_shift_u32(src_p[44], 0u, 0xffu);
    dst_p->led_15 = unpack_left_shift_u32(src_p[45], 16u, 0xffu);
    dst_p->led_15 |= unpack_left_shift_u32(src_p[46], 8u, 0xffu);
    dst_p->led_15 |= unpack_right_shift_u32(src_p[47], 0u, 0xffu);
    dst_p->led_16 = unpack_left_shift_u32(src_p[48], 16u, 0xffu);
    dst_p->led_16 |= unpack_left_shift_u32(src_p[49], 8u, 0xffu);
    dst_p->led_16 |= unpack_right_shift_u32(src_p[50], 0u, 0xffu);
    dst_p->led_17 = unpack_left_shift_u32(src_p[51], 16u, 0xffu);
    dst_p->led_17 |= unpack_left_shift_u32(src_p[52], 8u, 0xffu);
    dst_p->led_17 |= unpack_right_shift_u32(src_p[53], 0u, 0xffu);
    dst_p->led_18 = unpack_left_shift_u32(src_p[54], 16u, 0xffu);
    dst_p->led_18 |= unpack_left_shift_u32(src_p[55], 8u, 0xffu);
    dst_p->led_18 |= unpack_right_shift_u32(src_p[56], 0u, 0xffu);
    dst_p->led_19 = unpack_left_shift_u32(src_p[57], 16u, 0xffu);
    dst_p->led_19 |= unpack_left_shift_u32(src_p[58], 8u, 0xffu);
    dst_p->led_19 |= unpack_right_shift_u32(src_p[59], 0u, 0xffu);
    dst_p->led_20 = unpack_left_shift_u32(src_p[60], 16u, 0xffu);
    dst_p->led_20 |= unpack_left_shift_u32(src_p[61], 8u, 0xffu);
    dst_p->led_20 |= unpack_right_shift_u32(src_p[62], 0u, 0xffu);
    dst_p->brightness = unpack_right_shift_u8(src_p[63], 0u, 0xffu);

    return (0);
}

int display_neopixel_init(struct display_neopixel_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct display_neopixel_t));

    return 0;
}

uint32_t display_neopixel_led_00_encode(double value)
{
    return (uint32_t)(value);
}

double display_neopixel_led_00_decode(uint32_t value)
{
    return ((double)value);
}

bool display_neopixel_led_00_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

bool display_neopixel_led_00_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint32_t display_neopixel_led_01_encode(double value)
{
    return (uint32_t)(value);
}

double display_neopixel_led_01_decode(uint32_t value)
{
    return ((double)value);
}

bool display_neopixel_led_01_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

bool display_neopixel_led_01_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint32_t display_neopixel_led_02_encode(double value)
{
    return (uint32_t)(value);
}

double display_neopixel_led_02_decode(uint32_t value)
{
    return ((double)value);
}

bool display_neopixel_led_02_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

bool display_neopixel_led_02_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint32_t display_neopixel_led_03_encode(double value)
{
    return (uint32_t)(value);
}

double display_neopixel_led_03_decode(uint32_t value)
{
    return ((double)value);
}

bool display_neopixel_led_03_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

bool display_neopixel_led_03_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint32_t display_neopixel_led_04_encode(double value)
{
    return (uint32_t)(value);
}

double display_neopixel_led_04_decode(uint32_t value)
{
    return ((double)value);
}

bool display_neopixel_led_04_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

bool display_neopixel_led_04_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint32_t display_neopixel_led_05_encode(double value)
{
    return (uint32_t)(value);
}

double display_neopixel_led_05_decode(uint32_t value)
{
    return ((double)value);
}

bool display_neopixel_led_05_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

bool display_neopixel_led_05_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint32_t display_neopixel_led_06_encode(double value)
{
    return (uint32_t)(value);
}

double display_neopixel_led_06_decode(uint32_t value)
{
    return ((double)value);
}

bool display_neopixel_led_06_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

bool display_neopixel_led_06_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint32_t display_neopixel_led_07_encode(double value)
{
    return (uint32_t)(value);
}

double display_neopixel_led_07_decode(uint32_t value)
{
    return ((double)value);
}

bool display_neopixel_led_07_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

bool display_neopixel_led_07_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint32_t display_neopixel_led_08_encode(double value)
{
    return (uint32_t)(value);
}

double display_neopixel_led_08_decode(uint32_t value)
{
    return ((double)value);
}

bool display_neopixel_led_08_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

bool display_neopixel_led_08_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint32_t display_neopixel_led_09_encode(double value)
{
    return (uint32_t)(value);
}

double display_neopixel_led_09_decode(uint32_t value)
{
    return ((double)value);
}

bool display_neopixel_led_09_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

bool display_neopixel_led_09_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint32_t display_neopixel_led_10_encode(double value)
{
    return (uint32_t)(value);
}

double display_neopixel_led_10_decode(uint32_t value)
{
    return ((double)value);
}

bool display_neopixel_led_10_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

bool display_neopixel_led_10_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint32_t display_neopixel_led_11_encode(double value)
{
    return (uint32_t)(value);
}

double display_neopixel_led_11_decode(uint32_t value)
{
    return ((double)value);
}

bool display_neopixel_led_11_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

bool display_neopixel_led_11_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint32_t display_neopixel_led_12_encode(double value)
{
    return (uint32_t)(value);
}

double display_neopixel_led_12_decode(uint32_t value)
{
    return ((double)value);
}

bool display_neopixel_led_12_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

bool display_neopixel_led_12_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint32_t display_neopixel_led_13_encode(double value)
{
    return (uint32_t)(value);
}

double display_neopixel_led_13_decode(uint32_t value)
{
    return ((double)value);
}

bool display_neopixel_led_13_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

bool display_neopixel_led_13_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint32_t display_neopixel_led_14_encode(double value)
{
    return (uint32_t)(value);
}

double display_neopixel_led_14_decode(uint32_t value)
{
    return ((double)value);
}

bool display_neopixel_led_14_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

bool display_neopixel_led_14_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint32_t display_neopixel_led_15_encode(double value)
{
    return (uint32_t)(value);
}

double display_neopixel_led_15_decode(uint32_t value)
{
    return ((double)value);
}

bool display_neopixel_led_15_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

bool display_neopixel_led_15_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint32_t display_neopixel_led_16_encode(double value)
{
    return (uint32_t)(value);
}

double display_neopixel_led_16_decode(uint32_t value)
{
    return ((double)value);
}

bool display_neopixel_led_16_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

bool display_neopixel_led_16_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint32_t display_neopixel_led_17_encode(double value)
{
    return (uint32_t)(value);
}

double display_neopixel_led_17_decode(uint32_t value)
{
    return ((double)value);
}

bool display_neopixel_led_17_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

bool display_neopixel_led_17_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint32_t display_neopixel_led_18_encode(double value)
{
    return (uint32_t)(value);
}

double display_neopixel_led_18_decode(uint32_t value)
{
    return ((double)value);
}

bool display_neopixel_led_18_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

bool display_neopixel_led_18_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint32_t display_neopixel_led_19_encode(double value)
{
    return (uint32_t)(value);
}

double display_neopixel_led_19_decode(uint32_t value)
{
    return ((double)value);
}

bool display_neopixel_led_19_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

bool display_neopixel_led_19_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint32_t display_neopixel_led_20_encode(double value)
{
    return (uint32_t)(value);
}

double display_neopixel_led_20_decode(uint32_t value)
{
    return ((double)value);
}

bool display_neopixel_led_20_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

bool display_neopixel_led_20_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint8_t display_neopixel_brightness_encode(double value)
{
    return (uint8_t)(value);
}

double display_neopixel_brightness_decode(uint8_t value)
{
    return ((double)value);
}

bool display_neopixel_brightness_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool display_neopixel_brightness_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}
