/**
 * @file izze_imu_v2.c
 *
 * @brief This source file was generated by cantools version 43.0.2 Wed Sep  2 19:24:44 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "izze_imu_v2.h"

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int izze_imu_v2_angular_rate_rear_pack(
    uint8_t *dst_p,
    const struct izze_imu_v2_angular_rate_rear_t *src_p,
    size_t size)
{
    uint16_t rear_angular_x;
    uint16_t rear_angular_y;
    uint16_t rear_angular_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    rear_angular_x = (uint16_t)src_p->rear_angular_x;
    dst_p[0] |= pack_right_shift_u16(rear_angular_x, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(rear_angular_x, 0u, 0xffu);
    rear_angular_y = (uint16_t)src_p->rear_angular_y;
    dst_p[2] |= pack_right_shift_u16(rear_angular_y, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(rear_angular_y, 0u, 0xffu);
    rear_angular_z = (uint16_t)src_p->rear_angular_z;
    dst_p[4] |= pack_right_shift_u16(rear_angular_z, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(rear_angular_z, 0u, 0xffu);

    return (8);
}

int izze_imu_v2_angular_rate_rear_unpack(
    struct izze_imu_v2_angular_rate_rear_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t rear_angular_x;
    uint16_t rear_angular_y;
    uint16_t rear_angular_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    rear_angular_x = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    rear_angular_x |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->rear_angular_x = (int16_t)rear_angular_x;
    rear_angular_y = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    rear_angular_y |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->rear_angular_y = (int16_t)rear_angular_y;
    rear_angular_z = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    rear_angular_z |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->rear_angular_z = (int16_t)rear_angular_z;

    return (0);
}

int izze_imu_v2_angular_rate_rear_init(struct izze_imu_v2_angular_rate_rear_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct izze_imu_v2_angular_rate_rear_t));

    return 0;
}

int16_t izze_imu_v2_angular_rate_rear_rear_angular_x_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double izze_imu_v2_angular_rate_rear_rear_angular_x_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool izze_imu_v2_angular_rate_rear_rear_angular_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool izze_imu_v2_angular_rate_rear_rear_angular_x_is_in_phys_range(double value)
{
    return ((value >= -3276.8) && (value <= 3276.7));
}

int16_t izze_imu_v2_angular_rate_rear_rear_angular_y_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double izze_imu_v2_angular_rate_rear_rear_angular_y_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool izze_imu_v2_angular_rate_rear_rear_angular_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool izze_imu_v2_angular_rate_rear_rear_angular_y_is_in_phys_range(double value)
{
    return ((value >= -3276.8) && (value <= 3276.7));
}

int16_t izze_imu_v2_angular_rate_rear_rear_angular_z_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double izze_imu_v2_angular_rate_rear_rear_angular_z_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool izze_imu_v2_angular_rate_rear_rear_angular_z_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool izze_imu_v2_angular_rate_rear_rear_angular_z_is_in_phys_range(double value)
{
    return ((value >= -3276.8) && (value <= 3276.7));
}

int izze_imu_v2_acceleration_rear_pack(
    uint8_t *dst_p,
    const struct izze_imu_v2_acceleration_rear_t *src_p,
    size_t size)
{
    uint16_t rear_acc_x;
    uint16_t rear_acc_y;
    uint16_t rear_acc_z;
    uint16_t rear_imu_temp;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    rear_acc_x = (uint16_t)src_p->rear_acc_x;
    dst_p[0] |= pack_right_shift_u16(rear_acc_x, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(rear_acc_x, 0u, 0xffu);
    rear_acc_y = (uint16_t)src_p->rear_acc_y;
    dst_p[2] |= pack_right_shift_u16(rear_acc_y, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(rear_acc_y, 0u, 0xffu);
    rear_acc_z = (uint16_t)src_p->rear_acc_z;
    dst_p[4] |= pack_right_shift_u16(rear_acc_z, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(rear_acc_z, 0u, 0xffu);
    rear_imu_temp = (uint16_t)src_p->rear_imu_temp;
    dst_p[6] |= pack_right_shift_u16(rear_imu_temp, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(rear_imu_temp, 0u, 0xffu);

    return (8);
}

int izze_imu_v2_acceleration_rear_unpack(
    struct izze_imu_v2_acceleration_rear_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t rear_acc_x;
    uint16_t rear_acc_y;
    uint16_t rear_acc_z;
    uint16_t rear_imu_temp;

    if (size < 8u) {
        return (-EINVAL);
    }

    rear_acc_x = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    rear_acc_x |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->rear_acc_x = (int16_t)rear_acc_x;
    rear_acc_y = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    rear_acc_y |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->rear_acc_y = (int16_t)rear_acc_y;
    rear_acc_z = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    rear_acc_z |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->rear_acc_z = (int16_t)rear_acc_z;
    rear_imu_temp = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    rear_imu_temp |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
    dst_p->rear_imu_temp = (int16_t)rear_imu_temp;

    return (0);
}

int izze_imu_v2_acceleration_rear_init(struct izze_imu_v2_acceleration_rear_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct izze_imu_v2_acceleration_rear_t));

    return 0;
}

int16_t izze_imu_v2_acceleration_rear_rear_acc_x_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double izze_imu_v2_acceleration_rear_rear_acc_x_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool izze_imu_v2_acceleration_rear_rear_acc_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool izze_imu_v2_acceleration_rear_rear_acc_x_is_in_phys_range(double value)
{
    return ((value >= -327.68) && (value <= 327.67));
}

int16_t izze_imu_v2_acceleration_rear_rear_acc_y_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double izze_imu_v2_acceleration_rear_rear_acc_y_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool izze_imu_v2_acceleration_rear_rear_acc_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool izze_imu_v2_acceleration_rear_rear_acc_y_is_in_phys_range(double value)
{
    return ((value >= -327.68) && (value <= 327.67));
}

int16_t izze_imu_v2_acceleration_rear_rear_acc_z_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double izze_imu_v2_acceleration_rear_rear_acc_z_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool izze_imu_v2_acceleration_rear_rear_acc_z_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool izze_imu_v2_acceleration_rear_rear_acc_z_is_in_phys_range(double value)
{
    return ((value >= -327.68) && (value <= 327.67));
}

int16_t izze_imu_v2_acceleration_rear_rear_imu_temp_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double izze_imu_v2_acceleration_rear_rear_imu_temp_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool izze_imu_v2_acceleration_rear_rear_imu_temp_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool izze_imu_v2_acceleration_rear_rear_imu_temp_is_in_phys_range(double value)
{
    return ((value >= -32768.0) && (value <= 32767.0));
}

int izze_imu_v2_acceleration_front_pack(
    uint8_t *dst_p,
    const struct izze_imu_v2_acceleration_front_t *src_p,
    size_t size)
{
    uint16_t front_acc_x;
    uint16_t front_acc_y;
    uint16_t front_acc_z;
    uint16_t front_imu_temp;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    front_acc_x = (uint16_t)src_p->front_acc_x;
    dst_p[0] |= pack_right_shift_u16(front_acc_x, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(front_acc_x, 0u, 0xffu);
    front_acc_y = (uint16_t)src_p->front_acc_y;
    dst_p[2] |= pack_right_shift_u16(front_acc_y, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(front_acc_y, 0u, 0xffu);
    front_acc_z = (uint16_t)src_p->front_acc_z;
    dst_p[4] |= pack_right_shift_u16(front_acc_z, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(front_acc_z, 0u, 0xffu);
    front_imu_temp = (uint16_t)src_p->front_imu_temp;
    dst_p[6] |= pack_right_shift_u16(front_imu_temp, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(front_imu_temp, 0u, 0xffu);

    return (8);
}

int izze_imu_v2_acceleration_front_unpack(
    struct izze_imu_v2_acceleration_front_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t front_acc_x;
    uint16_t front_acc_y;
    uint16_t front_acc_z;
    uint16_t front_imu_temp;

    if (size < 8u) {
        return (-EINVAL);
    }

    front_acc_x = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    front_acc_x |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->front_acc_x = (int16_t)front_acc_x;
    front_acc_y = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    front_acc_y |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->front_acc_y = (int16_t)front_acc_y;
    front_acc_z = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    front_acc_z |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->front_acc_z = (int16_t)front_acc_z;
    front_imu_temp = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    front_imu_temp |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
    dst_p->front_imu_temp = (int16_t)front_imu_temp;

    return (0);
}

int izze_imu_v2_acceleration_front_init(struct izze_imu_v2_acceleration_front_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct izze_imu_v2_acceleration_front_t));

    return 0;
}

int16_t izze_imu_v2_acceleration_front_front_acc_x_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double izze_imu_v2_acceleration_front_front_acc_x_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool izze_imu_v2_acceleration_front_front_acc_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool izze_imu_v2_acceleration_front_front_acc_x_is_in_phys_range(double value)
{
    return ((value >= -327.68) && (value <= 327.67));
}

int16_t izze_imu_v2_acceleration_front_front_acc_y_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double izze_imu_v2_acceleration_front_front_acc_y_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool izze_imu_v2_acceleration_front_front_acc_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool izze_imu_v2_acceleration_front_front_acc_y_is_in_phys_range(double value)
{
    return ((value >= -327.68) && (value <= 327.67));
}

int16_t izze_imu_v2_acceleration_front_front_acc_z_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double izze_imu_v2_acceleration_front_front_acc_z_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool izze_imu_v2_acceleration_front_front_acc_z_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool izze_imu_v2_acceleration_front_front_acc_z_is_in_phys_range(double value)
{
    return ((value >= -327.68) && (value <= 327.67));
}

int16_t izze_imu_v2_acceleration_front_front_imu_temp_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double izze_imu_v2_acceleration_front_front_imu_temp_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool izze_imu_v2_acceleration_front_front_imu_temp_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool izze_imu_v2_acceleration_front_front_imu_temp_is_in_phys_range(double value)
{
    return ((value >= -32768.0) && (value <= 32767.0));
}

int izze_imu_v2_angular_rate_front_pack(
    uint8_t *dst_p,
    const struct izze_imu_v2_angular_rate_front_t *src_p,
    size_t size)
{
    uint16_t front_angular_x;
    uint16_t front_angular_y;
    uint16_t front_angular_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    front_angular_x = (uint16_t)src_p->front_angular_x;
    dst_p[0] |= pack_right_shift_u16(front_angular_x, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(front_angular_x, 0u, 0xffu);
    front_angular_y = (uint16_t)src_p->front_angular_y;
    dst_p[2] |= pack_right_shift_u16(front_angular_y, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(front_angular_y, 0u, 0xffu);
    front_angular_z = (uint16_t)src_p->front_angular_z;
    dst_p[4] |= pack_right_shift_u16(front_angular_z, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(front_angular_z, 0u, 0xffu);

    return (8);
}

int izze_imu_v2_angular_rate_front_unpack(
    struct izze_imu_v2_angular_rate_front_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t front_angular_x;
    uint16_t front_angular_y;
    uint16_t front_angular_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    front_angular_x = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    front_angular_x |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->front_angular_x = (int16_t)front_angular_x;
    front_angular_y = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    front_angular_y |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->front_angular_y = (int16_t)front_angular_y;
    front_angular_z = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    front_angular_z |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->front_angular_z = (int16_t)front_angular_z;

    return (0);
}

int izze_imu_v2_angular_rate_front_init(struct izze_imu_v2_angular_rate_front_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct izze_imu_v2_angular_rate_front_t));

    return 0;
}

int16_t izze_imu_v2_angular_rate_front_front_angular_x_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double izze_imu_v2_angular_rate_front_front_angular_x_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool izze_imu_v2_angular_rate_front_front_angular_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool izze_imu_v2_angular_rate_front_front_angular_x_is_in_phys_range(double value)
{
    return ((value >= -3276.8) && (value <= 3276.7));
}

int16_t izze_imu_v2_angular_rate_front_front_angular_y_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double izze_imu_v2_angular_rate_front_front_angular_y_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool izze_imu_v2_angular_rate_front_front_angular_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool izze_imu_v2_angular_rate_front_front_angular_y_is_in_phys_range(double value)
{
    return ((value >= -3276.8) && (value <= 3276.7));
}

int16_t izze_imu_v2_angular_rate_front_front_angular_z_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double izze_imu_v2_angular_rate_front_front_angular_z_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool izze_imu_v2_angular_rate_front_front_angular_z_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool izze_imu_v2_angular_rate_front_front_angular_z_is_in_phys_range(double value)
{
    return ((value >= -3276.8) && (value <= 3276.7));
}
