/**
 * @file izze_imu_v2.h
 *
 * @brief This header file was generated by cantools version 43.0.2 Tue Sep  1 22:13:44 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef IZZE_IMU_V2_H
#define IZZE_IMU_V2_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define IZZE_IMU_V2_ANGULAR_RATE_REAR_FRAME_ID (0x4eeu)
#define IZZE_IMU_V2_ACCELERATION_REAR_FRAME_ID (0x4efu)
#define IZZE_IMU_V2_ACCELERATION_FRONT_FRAME_ID (0x4edu)
#define IZZE_IMU_V2_ANGULAR_RATE_FRONT_FRAME_ID (0x4ecu)

/* Frame lengths in bytes. */
#define IZZE_IMU_V2_ANGULAR_RATE_REAR_LENGTH (8u)
#define IZZE_IMU_V2_ACCELERATION_REAR_LENGTH (8u)
#define IZZE_IMU_V2_ACCELERATION_FRONT_LENGTH (8u)
#define IZZE_IMU_V2_ANGULAR_RATE_FRONT_LENGTH (8u)

/* Extended or standard frame types. */
#define IZZE_IMU_V2_ANGULAR_RATE_REAR_IS_EXTENDED (0)
#define IZZE_IMU_V2_ACCELERATION_REAR_IS_EXTENDED (0)
#define IZZE_IMU_V2_ACCELERATION_FRONT_IS_EXTENDED (0)
#define IZZE_IMU_V2_ANGULAR_RATE_FRONT_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */
#define IZZE_IMU_V2_ANGULAR_RATE_REAR_CYCLE_TIME_MS (20u)
#define IZZE_IMU_V2_ACCELERATION_REAR_CYCLE_TIME_MS (20u)
#define IZZE_IMU_V2_ACCELERATION_FRONT_CYCLE_TIME_MS (20u)
#define IZZE_IMU_V2_ANGULAR_RATE_FRONT_CYCLE_TIME_MS (20u)

/* Signal choices. */


/* Frame Names. */
#define IZZE_IMU_V2_ANGULAR_RATE_REAR_NAME "Angular_Rate_Rear"
#define IZZE_IMU_V2_ACCELERATION_REAR_NAME "Acceleration_Rear"
#define IZZE_IMU_V2_ACCELERATION_FRONT_NAME "Acceleration_Front"
#define IZZE_IMU_V2_ANGULAR_RATE_FRONT_NAME "Angular_Rate_Front"

/* Signal Names. */
#define IZZE_IMU_V2_ANGULAR_RATE_REAR_REAR_ANGULAR_X_NAME "rear_angular_x"
#define IZZE_IMU_V2_ANGULAR_RATE_REAR_REAR_ANGULAR_Y_NAME "rear_angular_y"
#define IZZE_IMU_V2_ANGULAR_RATE_REAR_REAR_ANGULAR_Z_NAME "rear_angular_z"
#define IZZE_IMU_V2_ACCELERATION_REAR_REAR_ACC_X_NAME "rear_acc_x"
#define IZZE_IMU_V2_ACCELERATION_REAR_REAR_ACC_Y_NAME "rear_acc_y"
#define IZZE_IMU_V2_ACCELERATION_REAR_REAR_ACC_Z_NAME "rear_acc_z"
#define IZZE_IMU_V2_ACCELERATION_REAR_REAR_IMU_TEMP_NAME "rear_imu_temp"
#define IZZE_IMU_V2_ACCELERATION_FRONT_FRONT_ACC_X_NAME "front_acc_x"
#define IZZE_IMU_V2_ACCELERATION_FRONT_FRONT_ACC_Y_NAME "front_acc_y"
#define IZZE_IMU_V2_ACCELERATION_FRONT_FRONT_ACC_Z_NAME "front_acc_z"
#define IZZE_IMU_V2_ACCELERATION_FRONT_FRONT_IMU_TEMP_NAME "front_imu_temp"
#define IZZE_IMU_V2_ANGULAR_RATE_FRONT_FRONT_ANGULAR_X_NAME "front_angular_x"
#define IZZE_IMU_V2_ANGULAR_RATE_FRONT_FRONT_ANGULAR_Y_NAME "front_angular_y"
#define IZZE_IMU_V2_ANGULAR_RATE_FRONT_FRONT_ANGULAR_Z_NAME "front_angular_z"

/**
 * Signals in message Angular_Rate_Rear.
 *
 * All signal values are as on the CAN bus.
 */
struct izze_imu_v2_angular_rate_rear_t {
    /**
     * Range: -32768..32767 (-3276.8..3276.7 deg/sec)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t rear_angular_x;

    /**
     * Range: -32768..32767 (-3276.8..3276.7 deg/sec)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t rear_angular_y;

    /**
     * Range: -32768..32767 (-3276.8..3276.7 deg/sec)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t rear_angular_z;
};

/**
 * Signals in message Acceleration_Rear.
 *
 * All signal values are as on the CAN bus.
 */
struct izze_imu_v2_acceleration_rear_t {
    /**
     * Range: -32768..32767 (-327.68..327.67 g)
     * Scale: 0.01
     * Offset: 0
     */
    int16_t rear_acc_x;

    /**
     * Range: -32768..32767 (-327.68..327.67 g)
     * Scale: 0.01
     * Offset: 0
     */
    int16_t rear_acc_y;

    /**
     * Range: -32768..32767 (-327.68..327.67 g)
     * Scale: 0.01
     * Offset: 0
     */
    int16_t rear_acc_z;

    /**
     * Range: -327680..327670 (-32768..32767 C)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t rear_imu_temp;
};

/**
 * Signals in message Acceleration_Front.
 *
 * All signal values are as on the CAN bus.
 */
struct izze_imu_v2_acceleration_front_t {
    /**
     * Range: -32768..32767 (-327.68..327.67 g)
     * Scale: 0.01
     * Offset: 0
     */
    int16_t front_acc_x;

    /**
     * Range: -32768..32767 (-327.68..327.67 g)
     * Scale: 0.01
     * Offset: 0
     */
    int16_t front_acc_y;

    /**
     * Range: -32768..32767 (-327.68..327.67 g)
     * Scale: 0.01
     * Offset: 0
     */
    int16_t front_acc_z;

    /**
     * Range: -327680..327670 (-32768..32767 C)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t front_imu_temp;
};

/**
 * Signals in message Angular_Rate_Front.
 *
 * All signal values are as on the CAN bus.
 */
struct izze_imu_v2_angular_rate_front_t {
    /**
     * Range: -32768..32767 (-3276.8..3276.7 deg/sec)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t front_angular_x;

    /**
     * Range: -32768..32767 (-3276.8..3276.7 deg/sec)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t front_angular_y;

    /**
     * Range: -32768..32767 (-3276.8..3276.7 deg/sec)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t front_angular_z;
};

/**
 * Pack message Angular_Rate_Rear.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int izze_imu_v2_angular_rate_rear_pack(
    uint8_t *dst_p,
    const struct izze_imu_v2_angular_rate_rear_t *src_p,
    size_t size);

/**
 * Unpack message Angular_Rate_Rear.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int izze_imu_v2_angular_rate_rear_unpack(
    struct izze_imu_v2_angular_rate_rear_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Angular_Rate_Rear.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int izze_imu_v2_angular_rate_rear_init(struct izze_imu_v2_angular_rate_rear_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t izze_imu_v2_angular_rate_rear_rear_angular_x_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_imu_v2_angular_rate_rear_rear_angular_x_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_imu_v2_angular_rate_rear_rear_angular_x_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_imu_v2_angular_rate_rear_rear_angular_x_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t izze_imu_v2_angular_rate_rear_rear_angular_y_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_imu_v2_angular_rate_rear_rear_angular_y_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_imu_v2_angular_rate_rear_rear_angular_y_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_imu_v2_angular_rate_rear_rear_angular_y_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t izze_imu_v2_angular_rate_rear_rear_angular_z_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_imu_v2_angular_rate_rear_rear_angular_z_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_imu_v2_angular_rate_rear_rear_angular_z_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_imu_v2_angular_rate_rear_rear_angular_z_is_in_phys_range(double value);

/**
 * Pack message Acceleration_Rear.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int izze_imu_v2_acceleration_rear_pack(
    uint8_t *dst_p,
    const struct izze_imu_v2_acceleration_rear_t *src_p,
    size_t size);

/**
 * Unpack message Acceleration_Rear.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int izze_imu_v2_acceleration_rear_unpack(
    struct izze_imu_v2_acceleration_rear_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Acceleration_Rear.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int izze_imu_v2_acceleration_rear_init(struct izze_imu_v2_acceleration_rear_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t izze_imu_v2_acceleration_rear_rear_acc_x_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_imu_v2_acceleration_rear_rear_acc_x_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_imu_v2_acceleration_rear_rear_acc_x_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_imu_v2_acceleration_rear_rear_acc_x_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t izze_imu_v2_acceleration_rear_rear_acc_y_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_imu_v2_acceleration_rear_rear_acc_y_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_imu_v2_acceleration_rear_rear_acc_y_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_imu_v2_acceleration_rear_rear_acc_y_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t izze_imu_v2_acceleration_rear_rear_acc_z_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_imu_v2_acceleration_rear_rear_acc_z_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_imu_v2_acceleration_rear_rear_acc_z_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_imu_v2_acceleration_rear_rear_acc_z_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t izze_imu_v2_acceleration_rear_rear_imu_temp_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_imu_v2_acceleration_rear_rear_imu_temp_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_imu_v2_acceleration_rear_rear_imu_temp_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_imu_v2_acceleration_rear_rear_imu_temp_is_in_phys_range(double value);

/**
 * Pack message Acceleration_Front.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int izze_imu_v2_acceleration_front_pack(
    uint8_t *dst_p,
    const struct izze_imu_v2_acceleration_front_t *src_p,
    size_t size);

/**
 * Unpack message Acceleration_Front.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int izze_imu_v2_acceleration_front_unpack(
    struct izze_imu_v2_acceleration_front_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Acceleration_Front.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int izze_imu_v2_acceleration_front_init(struct izze_imu_v2_acceleration_front_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t izze_imu_v2_acceleration_front_front_acc_x_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_imu_v2_acceleration_front_front_acc_x_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_imu_v2_acceleration_front_front_acc_x_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_imu_v2_acceleration_front_front_acc_x_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t izze_imu_v2_acceleration_front_front_acc_y_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_imu_v2_acceleration_front_front_acc_y_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_imu_v2_acceleration_front_front_acc_y_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_imu_v2_acceleration_front_front_acc_y_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t izze_imu_v2_acceleration_front_front_acc_z_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_imu_v2_acceleration_front_front_acc_z_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_imu_v2_acceleration_front_front_acc_z_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_imu_v2_acceleration_front_front_acc_z_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t izze_imu_v2_acceleration_front_front_imu_temp_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_imu_v2_acceleration_front_front_imu_temp_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_imu_v2_acceleration_front_front_imu_temp_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_imu_v2_acceleration_front_front_imu_temp_is_in_phys_range(double value);

/**
 * Pack message Angular_Rate_Front.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int izze_imu_v2_angular_rate_front_pack(
    uint8_t *dst_p,
    const struct izze_imu_v2_angular_rate_front_t *src_p,
    size_t size);

/**
 * Unpack message Angular_Rate_Front.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int izze_imu_v2_angular_rate_front_unpack(
    struct izze_imu_v2_angular_rate_front_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Angular_Rate_Front.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int izze_imu_v2_angular_rate_front_init(struct izze_imu_v2_angular_rate_front_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t izze_imu_v2_angular_rate_front_front_angular_x_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_imu_v2_angular_rate_front_front_angular_x_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_imu_v2_angular_rate_front_front_angular_x_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_imu_v2_angular_rate_front_front_angular_x_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t izze_imu_v2_angular_rate_front_front_angular_y_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_imu_v2_angular_rate_front_front_angular_y_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_imu_v2_angular_rate_front_front_angular_y_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_imu_v2_angular_rate_front_front_angular_y_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t izze_imu_v2_angular_rate_front_front_angular_z_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_imu_v2_angular_rate_front_front_angular_z_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_imu_v2_angular_rate_front_front_angular_z_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_imu_v2_angular_rate_front_front_angular_z_is_in_phys_range(double value);


#ifdef __cplusplus
}
#endif

#endif
