#pragma once
#include "izze_imu_v2.h"

#define izze_imu_v2_h IZZE_IMU_V2_H
#define izze_imu_v2_angular_rate_rear_frame_id IZZE_IMU_V2_ANGULAR_RATE_REAR_FRAME_ID
#define izze_imu_v2_acceleration_rear_frame_id IZZE_IMU_V2_ACCELERATION_REAR_FRAME_ID
#define izze_imu_v2_acceleration_front_frame_id IZZE_IMU_V2_ACCELERATION_FRONT_FRAME_ID
#define izze_imu_v2_angular_rate_front_frame_id IZZE_IMU_V2_ANGULAR_RATE_FRONT_FRAME_ID
#define izze_imu_v2_angular_rate_rear_length IZZE_IMU_V2_ANGULAR_RATE_REAR_LENGTH
#define izze_imu_v2_acceleration_rear_length IZZE_IMU_V2_ACCELERATION_REAR_LENGTH
#define izze_imu_v2_acceleration_front_length IZZE_IMU_V2_ACCELERATION_FRONT_LENGTH
#define izze_imu_v2_angular_rate_front_length IZZE_IMU_V2_ANGULAR_RATE_FRONT_LENGTH
#define izze_imu_v2_angular_rate_rear_is_extended IZZE_IMU_V2_ANGULAR_RATE_REAR_IS_EXTENDED
#define izze_imu_v2_acceleration_rear_is_extended IZZE_IMU_V2_ACCELERATION_REAR_IS_EXTENDED
#define izze_imu_v2_acceleration_front_is_extended IZZE_IMU_V2_ACCELERATION_FRONT_IS_EXTENDED
#define izze_imu_v2_angular_rate_front_is_extended IZZE_IMU_V2_ANGULAR_RATE_FRONT_IS_EXTENDED
#define izze_imu_v2_angular_rate_rear_cycle_time_ms IZZE_IMU_V2_ANGULAR_RATE_REAR_CYCLE_TIME_MS
#define izze_imu_v2_acceleration_rear_cycle_time_ms IZZE_IMU_V2_ACCELERATION_REAR_CYCLE_TIME_MS
#define izze_imu_v2_acceleration_front_cycle_time_ms IZZE_IMU_V2_ACCELERATION_FRONT_CYCLE_TIME_MS
#define izze_imu_v2_angular_rate_front_cycle_time_ms IZZE_IMU_V2_ANGULAR_RATE_FRONT_CYCLE_TIME_MS
#define izze_imu_v2_angular_rate_rear_name IZZE_IMU_V2_ANGULAR_RATE_REAR_NAME
#define izze_imu_v2_acceleration_rear_name IZZE_IMU_V2_ACCELERATION_REAR_NAME
#define izze_imu_v2_acceleration_front_name IZZE_IMU_V2_ACCELERATION_FRONT_NAME
#define izze_imu_v2_angular_rate_front_name IZZE_IMU_V2_ANGULAR_RATE_FRONT_NAME
#define izze_imu_v2_angular_rate_rear_rear_angular_x_name IZZE_IMU_V2_ANGULAR_RATE_REAR_REAR_ANGULAR_X_NAME
#define izze_imu_v2_angular_rate_rear_rear_angular_y_name IZZE_IMU_V2_ANGULAR_RATE_REAR_REAR_ANGULAR_Y_NAME
#define izze_imu_v2_angular_rate_rear_rear_angular_z_name IZZE_IMU_V2_ANGULAR_RATE_REAR_REAR_ANGULAR_Z_NAME
#define izze_imu_v2_acceleration_rear_rear_acc_x_name IZZE_IMU_V2_ACCELERATION_REAR_REAR_ACC_X_NAME
#define izze_imu_v2_acceleration_rear_rear_acc_y_name IZZE_IMU_V2_ACCELERATION_REAR_REAR_ACC_Y_NAME
#define izze_imu_v2_acceleration_rear_rear_acc_z_name IZZE_IMU_V2_ACCELERATION_REAR_REAR_ACC_Z_NAME
#define izze_imu_v2_acceleration_rear_rear_imu_temp_name IZZE_IMU_V2_ACCELERATION_REAR_REAR_IMU_TEMP_NAME
#define izze_imu_v2_acceleration_front_front_acc_x_name IZZE_IMU_V2_ACCELERATION_FRONT_FRONT_ACC_X_NAME
#define izze_imu_v2_acceleration_front_front_acc_y_name IZZE_IMU_V2_ACCELERATION_FRONT_FRONT_ACC_Y_NAME
#define izze_imu_v2_acceleration_front_front_acc_z_name IZZE_IMU_V2_ACCELERATION_FRONT_FRONT_ACC_Z_NAME
#define izze_imu_v2_acceleration_front_front_imu_temp_name IZZE_IMU_V2_ACCELERATION_FRONT_FRONT_IMU_TEMP_NAME
#define izze_imu_v2_angular_rate_front_front_angular_x_name IZZE_IMU_V2_ANGULAR_RATE_FRONT_FRONT_ANGULAR_X_NAME
#define izze_imu_v2_angular_rate_front_front_angular_y_name IZZE_IMU_V2_ANGULAR_RATE_FRONT_FRONT_ANGULAR_Y_NAME
#define izze_imu_v2_angular_rate_front_front_angular_z_name IZZE_IMU_V2_ANGULAR_RATE_FRONT_FRONT_ANGULAR_Z_NAME
