/**
 * @file xlog.c
 *
 * @brief This source file was generated by cantools version 43.0.2 Tue Sep  1 22:13:44 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "xlog.h"

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int xlog_lap_time_pack(
    uint8_t *dst_p,
    const struct xlog_lap_time_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u32(src_p->lap_time, 24u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->lap_time, 16u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->lap_time, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u32(src_p->lap_time, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(src_p->ref_time, 24u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->ref_time, 16u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->ref_time, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u32(src_p->ref_time, 0u, 0xffu);

    return (8);
}

int xlog_lap_time_unpack(
    struct xlog_lap_time_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->lap_time = unpack_left_shift_u32(src_p[0], 24u, 0xffu);
    dst_p->lap_time |= unpack_left_shift_u32(src_p[1], 16u, 0xffu);
    dst_p->lap_time |= unpack_left_shift_u32(src_p[2], 8u, 0xffu);
    dst_p->lap_time |= unpack_right_shift_u32(src_p[3], 0u, 0xffu);
    dst_p->ref_time = unpack_left_shift_u32(src_p[4], 24u, 0xffu);
    dst_p->ref_time |= unpack_left_shift_u32(src_p[5], 16u, 0xffu);
    dst_p->ref_time |= unpack_left_shift_u32(src_p[6], 8u, 0xffu);
    dst_p->ref_time |= unpack_right_shift_u32(src_p[7], 0u, 0xffu);

    return (0);
}

int xlog_lap_time_init(struct xlog_lap_time_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct xlog_lap_time_t));

    return 0;
}

uint32_t xlog_lap_time_lap_time_encode(double value)
{
    return (uint32_t)(value);
}

double xlog_lap_time_lap_time_decode(uint32_t value)
{
    return ((double)value);
}

bool xlog_lap_time_lap_time_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

bool xlog_lap_time_lap_time_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint32_t xlog_lap_time_ref_time_encode(double value)
{
    return (uint32_t)(value);
}

double xlog_lap_time_ref_time_decode(uint32_t value)
{
    return ((double)value);
}

bool xlog_lap_time_ref_time_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

bool xlog_lap_time_ref_time_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

int xlog_lap_pack(
    uint8_t *dst_p,
    const struct xlog_lap_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_right_shift_u16(src_p->lap, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->lap, 0u, 0xffu);

    return (2);
}

int xlog_lap_unpack(
    struct xlog_lap_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->lap = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->lap |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);

    return (0);
}

int xlog_lap_init(struct xlog_lap_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct xlog_lap_t));

    return 0;
}

uint16_t xlog_lap_lap_encode(double value)
{
    return (uint16_t)(value);
}

double xlog_lap_lap_decode(uint16_t value)
{
    return ((double)value);
}

bool xlog_lap_lap_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool xlog_lap_lap_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}
