/**
 * @file xlog.h
 *
 * @brief This header file was generated by cantools version 43.0.2 Tue Sep  1 22:13:44 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef XLOG_H
#define XLOG_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define XLOG_LAP_TIME_FRAME_ID (0x4001u)
#define XLOG_LAP_FRAME_ID (0x4000u)

/* Frame lengths in bytes. */
#define XLOG_LAP_TIME_LENGTH (8u)
#define XLOG_LAP_LENGTH (2u)

/* Extended or standard frame types. */
#define XLOG_LAP_TIME_IS_EXTENDED (1)
#define XLOG_LAP_IS_EXTENDED (1)

/* Frame cycle times in milliseconds. */


/* Signal choices. */


/* Frame Names. */
#define XLOG_LAP_TIME_NAME "lap_time"
#define XLOG_LAP_NAME "lap"

/* Signal Names. */
#define XLOG_LAP_TIME_LAP_TIME_NAME "lap_time"
#define XLOG_LAP_TIME_REF_TIME_NAME "ref_time"
#define XLOG_LAP_LAP_NAME "lap"

/**
 * Signals in message lap_time.
 *
 * All signal values are as on the CAN bus.
 */
struct xlog_lap_time_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint32_t lap_time;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint32_t ref_time;
};

/**
 * Signals in message lap.
 *
 * All signal values are as on the CAN bus.
 */
struct xlog_lap_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint16_t lap;
};

/**
 * Pack message lap_time.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int xlog_lap_time_pack(
    uint8_t *dst_p,
    const struct xlog_lap_time_t *src_p,
    size_t size);

/**
 * Unpack message lap_time.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int xlog_lap_time_unpack(
    struct xlog_lap_time_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from lap_time.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int xlog_lap_time_init(struct xlog_lap_time_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t xlog_lap_time_lap_time_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double xlog_lap_time_lap_time_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool xlog_lap_time_lap_time_is_in_range(uint32_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool xlog_lap_time_lap_time_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t xlog_lap_time_ref_time_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double xlog_lap_time_ref_time_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool xlog_lap_time_ref_time_is_in_range(uint32_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool xlog_lap_time_ref_time_is_in_phys_range(double value);

/**
 * Pack message lap.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int xlog_lap_pack(
    uint8_t *dst_p,
    const struct xlog_lap_t *src_p,
    size_t size);

/**
 * Unpack message lap.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int xlog_lap_unpack(
    struct xlog_lap_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from lap.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int xlog_lap_init(struct xlog_lap_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t xlog_lap_lap_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double xlog_lap_lap_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool xlog_lap_lap_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool xlog_lap_lap_is_in_phys_range(double value);


#ifdef __cplusplus
}
#endif

#endif
