/**
 * @file swc.c
 *
 * @brief This source file was generated by cantools version 43.0.2 Wed Sep  2 19:24:45 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "swc.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int swc_buttons_pack(
    uint8_t *dst_p,
    const struct swc_buttons_t *src_p,
    size_t size)
{
    uint16_t encoder_amount;

    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u8(src_p->encoder_button, 5u, 0x20u);
    encoder_amount = (uint16_t)src_p->encoder_amount;
    dst_p[1] |= pack_right_shift_u16(encoder_amount, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(encoder_amount, 0u, 0xffu);

    return (3);
}

int swc_buttons_unpack(
    struct swc_buttons_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t encoder_amount;

    if (size < 3u) {
        return (-EINVAL);
    }

    dst_p->encoder_button = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    encoder_amount = unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    encoder_amount |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->encoder_amount = (int16_t)encoder_amount;

    return (0);
}

int swc_buttons_init(struct swc_buttons_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct swc_buttons_t));

    return 0;
}

uint8_t swc_buttons_encoder_button_encode(double value)
{
    return (uint8_t)(value);
}

double swc_buttons_encoder_button_decode(uint8_t value)
{
    return ((double)value);
}

bool swc_buttons_encoder_button_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool swc_buttons_encoder_button_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

int16_t swc_buttons_encoder_amount_encode(double value)
{
    return (int16_t)(value);
}

double swc_buttons_encoder_amount_decode(int16_t value)
{
    return ((double)value);
}

bool swc_buttons_encoder_amount_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool swc_buttons_encoder_amount_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}
